server:
  port: 8000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/beam_db
    username: postgres
    password: 1357
  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

